name: Flask CI Smoke Test

# When should this be activated
on: [push, pull_request]

jobs:
  build-and-test:
    # 1 We can use Ubuntu Server in the cloud
    runs-on: ubuntu-latest

    # 2 Steps to build and test
    steps:
      # Checkout the code from the repo to the server
      - name: Checkout mode
        uses: actions/checkout@v3

      # Setting up python on the server
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install the project dependecies from requirement.txt
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # A smoke test to make sure the app works
      - name: Run smoke test
        run: |
          python -c "from app import app; print('App initialised successfully')"
        env:
          SECRET_KEY: "ci-testing-key"
          FLASK_ENV: "development"